### ISSUE TITLE
Old domain .io is not redirecting to the new one

### ISSUE THREAD

**Issue by JackSacali** [FalconX-DEX/Falx-Support#10]
**Describe the bug**
Seems like the DNS of falxdex.io is messed up

**To Reproduce**
1. Go to falxdex.io
2. You'll get "This site can’t be reached" with DNS_PROBE_FINISHED_NXDOMAIN

**Expected behavior**
Show a message explaining the motive behind the change to a new domain or at least just redirect to the new domain falxdex.com
It's still visible on solscan for example

**Screenshots**
n/a

**Desktop:**
any

**Smartphone:**
any

**Comment by Jk0x0kJ** [comment]
We will restore proper redirection as soon as possible.

@JackSacali
