### ISSUE TITLE
I have had a failed harvest, cannot see the FALX in my wallet

### ISSUE THREAD

**Issue by cheddarking** [FalconX-DEX/Falx-Support#11]
**Unable to harvest my Staking rewards**
I had rewards from staking my FALX and when I go to harvest it it says "Failed harvest". However the balance under harvest is now 0, but I have not received any FALX to my Phantom Wallet.

**Comment by Jk0x0kJ** [comment]
Could you please provide your wallet address? @cheddarking

**Comment by Jk0x0kJ** [comment]
This issue has been closed due to inactivity.
