### ISSUE TITLE
My walled has been  compromised

### ISSUE THREAD

**Issue by Ahmedh2400** [FalconX-DEX/Falx-Support#13]
Dear team 
My wallet has been compromised due to interaction with fake airdrops  now i have my tokens staked but the problem is i can't harvest , recieve airdrop cuz im top 100 or buy more to add to my account i wonder if there is a way to move to a new wallet my wallet address is D2bzANy6fBQQy3pkDFF5Xu5j5zRrN1aRCfSgkWrk4Le

**Comment by Jk0x0kJ** [comment]
As previously warned, interacting with malicious contracts can compromise your wallet address. These contracts have the ability to change the owner of the token account, leaving us unable to assist.

To confirm if your address has been affected, please provide it for verification.

@Ahmedh2400
