### ISSUE TITLE
Tuger staking 

### ISSUE THREAD

**Issue by F1can2020** [FalconX-DEX/Falx-Support#14]
**Describe the bug**
I have staked Tuger to harvest Falx but the value of staking rewards fluctuates up and down daily. Also my son has tried to stake his Tuger but the transaction doesn’t complete. 

**To Reproduce**
In my case I don’t have any steps to reproduce, I staked Tuger and the rewards have gone up, up then down, down, down and slightly up again. I don’t think it has anything to do with price. 

The other issue is just completing the usual staking steps with sufficient Tuger and Sol in the account for fees and transaction fails every time 

**Expected behavior**
that the volume of Falx would grow for the staked Tuger so that I could harvest and stake with my Falx 

that they would be able to stake their Tuger
![IMG_1444](https://github.com/FalconX-DEX/Falx-Support/assets/62806307/5493fc49-7794-4d46-93e4-66f30fae00cf)
![IMG_1509](https://github.com/FalconX-DEX/Falx-Support/assets/62806307/8a400d17-f6c5-4a47-bd5c-9e16c03012eb)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14 and iPhone 11
 - OS: up to date 17.5.1
 - Browser Phantom Wallet app
 

**Additional context**
The 1st screenshot shot was from 10/06/24 (400 odd Falx) and the 2nd screenshot is from today (17/06/24)

**Comment by Jk0x0kJ** [comment]
Could you please provide your wallet address?
@F1can2020

**Comment by F1can2020** [comment]
Hey thereWallet address is CkkopBn2byuzyZE95f66CZNnBoiLfymofESBiy4j9LE8RgdsFionaSent from my iPhoneOn 19 Jun 2024, at 08:11, Jk0x0kJ ***@***.***> wrote:﻿
Could you please provide your wallet address?
@F1can2020

**Comment by Jk0x0kJ** [comment]
For your information, the staking ratio only for FALX staking pool is 1:1, meaning each FALX token staked earns one reward token.

For other pools, the price of the base pool token is also important, as rewards are calculated based on the base token's price. The number of FALX reward tokens varies with the price changes of both TUGER according to FALX.

@F1can2020
