### ISSUE TITLE
Transferred Sol token to unknown wallet

### ISSUE THREAD

**Issue by Cisca70** [FalconX-DEX/Falx-Support#15]
I interacted with the Falxdex website when i wanted to check my staked token yesterday  and I noticed that the remaining falx token in my wallet was swapped to Sol token and sent to a certain wallet.  I can't say how it happened. 
I want to know how it happened because I just connected to only falx wallet.  I lost about 500k falx.
I will drop my wallet and the address the Sol token was sent to for further verification.
![Screenshot_20240619_054853_Chrome](https://github.com/FalconX-DEX/Falx-Support/assets/95353661/945273d8-eb93-46a4-9a2b-62be54308eb9)
![Screenshot_20240619_141651_Phantom](https://github.com/FalconX-DEX/Falx-Support/assets/95353661/1b2927da-bcc9-48c9-b29e-e1ff2191af53)
These are the wallets and the dates I interacted with them.
My wallet is FBJ7huNTdQ1P8KD53Kki68fWXmEfJ9gJfAfEcDHTtKvK
The address the Sol was sent to is
Crzw6RsrcPEkxSL1iMf71nRoFzLmaGK67rwsMaw7LW6a

**Comment by Lissanro** [comment]
Very sorry this happened to you, sounds like your wallet may be compromized. Our website is basically an UI to interact with our contracts, and only way our contracts can convert FALX to SOL is if you (or someone who got your private key or seed phrase) sign the transaction.

I suggest to urgently transfer your assets to a new wallet, created on a device with cleanly installed OS, or hardware wallet, with new seed phrase.

Please note that it is blockchain where all transactions are final. So if you think your wallet is compromised and someone can convert and transfer out tokens without your knowledge, transferring remaining assets to a new wallet is the best option.

If you still feel further investigation from our side is needed, please let us know.
