### ISSUE TITLE
concerned

### ISSUE THREAD

**Issue by CoinTuur** [FalconX-DEX/Falx-Support#16]
**Is your feature request related to a problem? Please describe.**
what is all the fuzz about the guy on YT (binancestuff), i am a little bit concerned about him, is he a treath to Falxdex?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Lissanro** [comment]
I don't know him, but there are no known "threats" to FalXDex, we develop according to our roadmap and have a great community. If this is still a topic you would like to discuss, please note that we have a Telegram chat with general topic. This github is for reporting issues with the website.
