### ISSUE TITLE
HARVEST Option not working countdown not showing

### ISSUE THREAD

**Issue by CHUDLPGC** [FalconX-DEX/Falx-Support#20]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CHUDLPGC** [comment]
Since last claim yesterday at 9am no countdown available and claim not posible. Cache deleted and tried other explores with no luck

**Comment by Lissanro** [comment]
Could you please provide your wallet address?

**Comment by CHUDLPGC** [comment]
Bellos wallet is 7Q9xV3KewrP6cDNrNisDup6g4K4C8hsQgKNL92WbP8uS
Thanks foenyour time

Sebastián J Pérez Alvarez
620 984 243
***@***.***

Enviado desde Proton Mail para Android

-------- Mensaje original --------
El 22/6/24 4:15, Lissanro Rayen  ha escrito:

**Comment by Jk0x0kJ** [comment]
A minor issue has been fixed. There should be no further problems now. @CHUDLPGC

**Comment by CHUDLPGC** [comment]
Thanks fornso quick response
Have a nice day

Sebastián J Pérez Alvarez
620 984 243
***@***.***

Enviado desde Proton Mail para Android

-------- Mensaje original --------
El 24/6/24 9:51, Jk0x0kJ  ha escrito:
