### ISSUE TITLE
Wrong pending rewards for staking Tuger

### ISSUE THREAD

**Issue by themuse1109** [FalconX-DEX/Falx-Support#21]
**Describe the bug**
Ever since I staked 5450 tuger, rewards are not showing up properly. Per my calculation, I have to get about 7 FALX daily. Now I have pending 3.9, and sometimes it shows even smaller amount than previous day, like 1 or 2 FALX pending. Thank you in advance for your help. 

**Screenshots**
![Snimka zaslona 2024-06-21 185803](https://github.com/FalconX-DEX/Falx-Support/assets/173490624/843c19cb-5704-4d4c-a252-1eb1f718f06c)

**Desktop (please complete the following information):**

 - Browser: Brave, latest version

**Comment by Jk0x0kJ** [comment]
This has already been mentioned in [this comment](https://github.com/FalconX-DEX/Falx-Support/issues/14#issuecomment-2185832107).


@themuse1109
