### ISSUE TITLE
**Un claimed falx no longer display in my tuger stacking**

### ISSUE THREAD

**Issue by Kato43** [FalconX-DEX/Falx-Support#22]
Unstacking of tuger before claiming my falx . 
So the falx cons where not harvested and no longer display there 
Wallet address. Phantom 
9M3c....ydkm
Date of unstacking 23rd June 2024
Time 7pm East Africa time

**Comment by Jk0x0kJ** [comment]
Please note that once you unstake your tokens, any accumulated rewards will be forfeited. Rewards are designed for stakers, and as soon as you unstake, the system removes you from the list of stakers and reward recipients.

To ensure you don't lose any rewards, please make sure to harvest them before unstaking your tokens.

@Kato43
