### ISSUE TITLE
Adding token contracts and swapping

### ISSUE THREAD

**Issue by captainbird** [FalconX-DEX/Falx-Support#23]
Uploading Screen_Recording_20240629_171645_Phantom.mp4…

Someone mentioned in telegram chat that they couldn't swap for Ponk or Land wolf tokens.
I don't want any ponk or land wolf but I tried adding both of those contracts on my end and that does work correctly but after you've added the contract and try to select either of those in the drop down it doesn't change the selection it just stays on Falx for some reason. Tried deleting cache, add/ readding, etc. I don't know if this happens for other added contacts but it's definitely not letting you select either of those to swap. 

Uploading Screen_Recording_20240629_171645_Phantom.mp4…

Included a screen recording of trying to select Ponk on both swap drop downs after adding the token contract

**Comment by Jk0x0kJ** [comment]
We noticed that your screen recordings were not uploaded properly, and we are unable to view them. When uploading a file to GitHub, please ensure the upload process is fully completed before closing the window or clicking on comment button. Could you please reupload the files and notify us once done? Thank you! @captainbird

**Comment by Jk0x0kJ** [comment]
closed due to inactivity.
