### ISSUE TITLE
No AirDrop from SolX times

### ISSUE THREAD

**Issue by MrOttiZ** [FalconX-DEX/Falx-Support#26]
Hi.

I have not received any AirDrop from my SolX stalking. I did fill out the form. 
DYeC9CbPsCzYgoAvrdYrgbo2MaE5v1cum2s3VLSd8tgg

**Comment by on2197** [comment]
I also did not get my airdrops for staking solx my wallet address  and I did filled out the form on time. User name is @on2197. 4PFPnk36MYZ1haULJCiKbXA2pMvb4BpsVUWCLcHWvfsa
Thank you,

**Comment by Lissanro** [comment]
Sorry but both addresses are not present in submitted form data. I double checked the original unprocessed data from the server, not there either. Perhaps you used a different address when submitting a form, or you did not submit within the time frame.

**Comment by on2197** [comment]
Are you serious this is the screen shot when I submitted my form. Peter O.On Jul 21, 2024, at 4:39 PM, Lissanro Rayen ***@***.***> wrote:﻿
Closed #26 as completed.

**Comment by on2197** [comment]
﻿Are you serious this is the screen shot when I submitted my form. Peter O.On Jul 21, 2024, at 4:39 PM, Lissanro Rayen ***@***.***> wrote:﻿
Closed #26 as completed.

**Comment by MrOttiZ** [comment]
No. I did submit a form with given adresse. How many forms have you guys
published?

søn. 21. juli 2024, 23:39 skrev Lissanro Rayen ***@***.***>:
