### ISSUE TITLE
The distributed airdrop didn't come to me

### ISSUE THREAD

**Issue by tegin12** [FalconX-DEX/Falx-Support#29]
**Describe the bug**

I made 2m stakes for the Solxdex project for those who airdrop distributed to the friends in the group, but nothing came to me, can you please check?

This is my wallet address where I trade. FzDZ4HLgzD4D2yuLJwdxK7SLqhuDVRFwejqwKXwLtMDx

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone14pro]
 - OS: [e.g. iOS 17.5.1]
 - Version [e.g. 23]

**Additional context**

**Comment by Lissanro** [comment]
I confirm that your wallet is in our list and it is eligible for airdrops, and I confirm your stake was about 2M. And the first airdrop already was sent to it, here is TXID:
5MB5XViHUEyMQnK5Diz36pXCzSP7ZrZPrXD5BKfsCRNwWtTnv3j57fn33pMhwUtCjMzdDdCjtZFDCPopGVYcwWG8

You will be getting airdrops weekly, for 33 weeks in total.

**Comment by tegin12** [comment]
I checked, nothing appears.

**Comment by Lissanro** [comment]
Please check the TXID I have provided, it is on the blockchain:

https://solscan.io/tx/5MB5XViHUEyMQnK5Diz36pXCzSP7ZrZPrXD5BKfsCRNwWtTnv3j57fn33pMhwUtCjMzdDdCjtZFDCPopGVYcwWG8
![Screenshot_20240722_145035](https://github.com/user-attachments/assets/a2fc9172-54f3-40f3-9227-4c6e415aed66)

The first airdrop is in your wallet, the transaction was successful.

**Comment by tegin12** [comment]
I'm so sorry, I just realized that the day they sent me, I bought falx and put it in stake, it was sent for 14k, thank you too, and I'm sorry again
