### ISSUE TITLE
Haven't Received Airdrop Allocation on my Stake SOLX Stake

### ISSUE THREAD

**Issue by artbluefaith** [FalconX-DEX/Falx-Support#30]
Please Re-Check my Waller Address

I also dont remember  filling out some for form.

7SzcUmCFegnM6cUqunxuAF3QpmsBjR51AwdBjsAmiSLd

Best Regards

**Comment by Lissanro** [comment]
Very sorry you missed airdrop allocation. I confirm that you did not submit the form, your address is not in the list.
