### ISSUE TITLE
solx airdrop

### ISSUE THREAD

**Issue by Digital1989** [FalconX-DEX/Falx-Support#32]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lissanro** [comment]
Sorry, you did not fill properly the bug report form, you just sent the unfilled template, and provided no relevant information. The title also does not mention any issues. Closing this bug report as invalid.

**Comment by Digital1989** [comment]
i know as i was checking i found the air dropps so i honestly dont need to sorry about that.

**Comment by Digital1989** [comment]
please close it and thank you
