### ISSUE TITLE
Didn't recieved solx airdrop

### ISSUE THREAD

**Issue by Rslin88** [FalconX-DEX/Falx-Support#34]
Haii,i'm stake solx and already filled the form before,but until now i didn't recieve my airdrop
Can you check it for me
My address 
GJWTrajBDAyoZgZzaNGC8zbaB22JxBrfCsQWEVXNhp2r

**Comment by Lissanro** [comment]
Sorry, but your address is not in the list, I double checked unprocessed user data from the server to be sure, your address wasn't there. So either you missed the submission period or the form wasn't successfully submitted.

**Comment by Rslin88** [comment]
But i submit the form twice for make sure,how can the form failed submit
So what the result?
