### ISSUE TITLE
Solx Airdrop

### ISSUE THREAD

**Issue by etermine236** [FalconX-DEX/Falx-Support#35]
Hi, I have never received any of the solx airdrop. I have filled the form twice to make sure it was sent.

Sol adress: F16KKbhrRcCsfiGiPV9LqhVNB76rGGhxr6WSzH1A332

**Comment by Lissanro** [comment]
Sorry, but your address is not in the list, I double checked unprocessed user data from the server to be sure, your address wasn't there. So either you missed the submission period or the form wasn't successfully submitted.
