### ISSUE TITLE
Did not receive airdrop

### ISSUE THREAD

**Issue by 420LT** [FalconX-DEX/Falx-Support#36]
I haven’t received airdrop. 
I filled the original claim form 
My wallet address is: 2Z2oAQnvJRYjH6x9ntk4751TXv6pDCCbR287TbDbU7Sm

**Comment by Lissanro** [comment]
Sorry, but your address is not in the list, I double checked unprocessed user data from the server to be sure, your address wasn't there. So either you missed the submission period or the form wasn't successfully submitted.
