### ISSUE TITLE
Airdrop from solx

### ISSUE THREAD

**Issue by Rslin88** [FalconX-DEX/Falx-Support#37]
haii can you check my adress
GJWTrajBDAyoZgZzaNGC8zbaB22JxBrfCsQWEVXNhp2r

Im already submit the form twice,but the team said im not submit

Matt ask me to here to resolve the problem

**Comment by Lissanro** [comment]
Sorry, but your address is not in the list, I double checked unprocessed user data from the server to be sure, your address wasn't there. So either you missed the submission period or the form wasn't successfully submitted.
