### ISSUE TITLE
Staking

### ISSUE THREAD

**Issue by danielagezez** [FalconX-DEX/Falx-Support#4]
I cant seem to be able to stake even with enough sol and money saved for the 1.5% in and out fee. Can you help. Thanks

**Comment by Lissanro** [comment]
We recently pushed some staking-related fixes, please try again. This should be solved.

In case you still experiencing the issue, please feel free to reopen and provide your wallet address, what browser and wallet app you are using, exact steps you are taking to attempt the stake and what exactly is the error you are getting.
