### ISSUE TITLE
Unable to harvest staking reward

### ISSUE THREAD

**Issue by CKS9999** [FalconX-DEX/Falx-Support#40]
**Describe the bug**
Dear support 

I have tried harvesting my staked reward but it keeping harvesting failed. I have over $4 worth Solana in my wallet. I noticed fees are being deducted when I confirm harvest but it is not letting harvest my reward. 

Never had this issue until today. I do daily harvest 

i have also clear cache on my Phantom wallet 

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS
 -

**Comment by Jk0x0kJ** [comment]
duplicated of #41 
please attach your wallet address to issue #41 
@CKS9999

**Comment by CKS9999** [comment]
> duplicated of #41 please attach your wallet address to issue #41 @CKS9999

4QB1m6MorkESmZo58y4QGZJqWNsMxnuHQ7MzN8yVx6mn

**Comment by CKS9999** [comment]
> duplicated of #41 please attach your wallet address to issue #41 @CKS9999

Not sure why this issue is closed because it still not working
