### ISSUE TITLE
unable to harvest

### ISSUE THREAD

**Issue by myvioletau** [FalconX-DEX/Falx-Support#41]
Dear Support Team,

just today, i cant harvet, the error says: failed to harvest,

the same error happened to me on iphone and on desktop
i cleared chrome browser cache, restart computer, closed and reopend browser, no good

please help!

my wallet address is : 

CSdsPxHRq4DqiU7JMFQv6RzkFWPg4BiGY9NJdbvE3rez

and i use Phantom wallet

please let me know if you need further information

thanks a lot!

Huy

**Comment by myvioletau** [comment]
![photo_2024-08-14_12-19-53](https://github.com/user-attachments/assets/55b098e4-8b1e-4124-b065-7849fa4a234a)

please see the photo for the actual error, thanks!

**Comment by myvioletau** [comment]
when i tried to harvest again, it stuck at : waiting for confirmation ....
and it actually taken the fee of 0.0002 SOL as shown below, but it never finish and i did not get any falx token
https://solscan.io/tx/5aZ87zpmLBhT3BpYQFzYhaKZQQfzBXMFEsdg1JzhmGH9xm4ZPHcZ1N2ZxWNuJMXnMaJ6SYYF4vVYJaRhpd1ctQYV

**Comment by myvioletau** [comment]
<img width="545" alt="image" src="https://github.com/user-attachments/assets/3b6287b5-524f-454a-88e2-837f8b51618a">

please see this photo

**Comment by myvioletau** [comment]
i just tried again and now, i got the confirmation :"failed harvest" as in this photo:

<img width="812" alt="image" src="https://github.com/user-attachments/assets/d8a1fe4f-cf6d-4190-b35f-00e216ac0e73">

**Comment by myvioletau** [comment]
i have $5.36 worth of SOL so, it is more than enough for the fee

**Comment by CKS9999** [comment]
Dear suport

I have also same exact problem and logged issue in github.

**Comment by myvioletau** [comment]
our main telegram chat group, i also found someone facing the same issue, they cant harvest the staking rewards now

it is the first time it failed on me

thanks!

**Comment by Jk0x0kJ** [comment]
please attach your wallet address @CKS9999

**Comment by CKS9999** [comment]
4QB1m6MorkESmZo58y4QGZJqWNsMxnuHQ7MzN8yVx6mn

**Comment by myvioletau** [comment]
my wallet address is :

CSdsPxHRq4DqiU7JMFQv6RzkFWPg4BiGY9NJdbvE3rez

**Comment by CKS9999** [comment]
Just noticed that my issue is closed on github. But when I tried to harvest
just now it is still giving me an failure error message.

**Comment by Jk0x0kJ** [comment]
your issue closed as its a duplication of this issue and we are checking both addresses for the same issue which is being unable to harvest @CKS9999

**Comment by Jk0x0kJ** [comment]
issue is fixed, please check it out from your ends @CKS9999 @myvioletau

**Comment by CKS9999** [comment]
Thank you. It is working now.

**Comment by myvioletau** [comment]
Excellent work! it is working fine now! thanks a lot guys!

**Comment by myvioletau** [comment]
what was the issue ? and will it likely to happen again or it is fixed permanently now ?

**Comment by Jk0x0kJ** [comment]
a minor precision checking issue, permanently fixed @myvioletau

**Comment by myvioletau** [comment]
thanks a lot for your time! i appreciate it
