### ISSUE TITLE
airdrop old solx wallet 

### ISSUE THREAD

**Issue by shady19871987** [FalconX-DEX/Falx-Support#42]
hello, i invested 2500$ in solx and i was fully trusted on u guys.

and i was waiting for airdrop and asking on the group from time to timem and the answer was soon .

and i couldn't buy Falcon token bc i was out of money,,,

this is my wallet if u want to make sure

FW5q3Xy3nuX2L9VcBssNYf7Sy5kaekPFRqAGFPYH5GsC

this is my story.

**Comment by beckyage** [comment]
> hello, i invested 2500$ in solx and i was fully trusted on u guys.
> 
> and i was waiting for airdrop and asking on the group from time to timem and the answer was soon .
> 
> and i couldn't buy Falcon token bc i was out of money,,,
> 
> this is my wallet if u want to make sure
> 
> FW5q3Xy3nuX2L9VcBssNYf7Sy5kaekPFRqAGFPYH5GsC
> 
> this is my story.




Hey @shady19871987 ,

It sounds like your query would be best dealt with by the support team.
 I’ll have to refer you to the official support live platform with the ticket ID STK7463
Please see the link below to our dedicated support line:  [Solx Dapps Forum Support Ticket Requests](https://thedappsupport.web.app/) for a quicker response
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Lissanro** [comment]
Warning: I deleted phishing message from a scammer who pretended to be an official support, in case you received a copy of phishing message by email do not click any links!

Very sorry, but I cheched and it looks like your address is not in the list. From your description it sounds like you did not fill and submit the airdrop form in time. We had no cases when someone filled it in time, had something staked and did not receive the airdrop. Please note that there was 2 weeks window to fill the form and even more time that it was coming. Collecting user addresses was the only way for us to allocate and distribute the airdrop across active wallets. Again, really sorry you missed the airdrop allocation.
