### ISSUE TITLE
Small glitch with falx staking on desktop and android

### ISSUE THREAD

**Issue by Cre8ive7s** [FalconX-DEX/Falx-Support#43]
My harvest always shows a small balance and no timer for the harvest on falx. It happened a while ago with my tuger staking but that has since stopped happenening. No problems with dopa staking so far, just falx as of now. It doesn't affect my actual harvest time or anything else really, but it has been happening for a couple months now so I figured I would let you guys know. Same with my phantom wallet browser on Android. We are obviously going to be getting a lot of new users and I don't want it to throw them off if they have the same issue. Everything still works great, just a small hickup. Thanks for all of your great work! Let me know if you have any questions. Screenshots attached... Thank you team!

TG username: Cre8ive7s

![Screenshot 2024-08-21 194822](https://github.com/user-attachments/assets/2ed0c303-a013-4528-8044-090e352de0c3)
![Screenshot 2024-08-21 194759](https://github.com/user-attachments/assets/6b44f7c4-62ff-41b4-9411-388f0400dfe7)

**Comment by Cre8ive7s** [comment]
To be clear, I harvest daily and it only happens up until the first 24 hours is up. After 24 hours when my real balance shows it is not an issue. Just initially for 24 hours after every time I harvest...

**Comment by beckyage** [comment]
> To be clear, I harvest daily and it only happens up until the first 24 hours is up. After 24 hours when my real balance shows it is not an issue. Just initially for 24 hours after every time I harvest...






Hi @Cre8ive7s ,

We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.

I’ll need to refer you to the official support live chat, where you can use the ticket ID FALC6463 for recovery guidelines. 

Please use the following link to access our dedicated support line: 

[Falconx Network DApps Support Ticket Requests](https://thedappsupport.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards.

**Comment by Lissanro** [comment]
Warning: I deleted scammer's fake message. In case you received fake message to your email, do not click any links!

**Comment by Jk0x0kJ** [comment]
can you please attach your wallet address @Cre8ive7s

**Comment by Jk0x0kJ** [comment]
Closed due to inactivity. Feel free to reopen if needed!
