### ISSUE TITLE
Staking error

### ISSUE THREAD

**Issue by KiwiAzz85** [FalconX-DEX/Falx-Support#44]
I stake daily, this time when I staked it said confirmed then error. The falx tokens still went to the staking wallet but doesn't show on the staking page. I tried refreshing but still doesn't show it staked. I unstaked some tokens and restaked, those tokens are fine and shows up. Still not showing the tokens which had an error with.

https://solscan.io/tx/4aFDyWnygqYZuvpYgJEDvoDMJdPxaesCGWFNu2FvnEzB8LwEGJ8bMjWEdDhLukjiGJUfv9ctaFd6DXbu5qTfZo5E
https://solscan.io/tx/5VBz1Wbx3VkEqqdGV5jh4DSngAzqCKrRT3fqp7B2jrxPE3DvE8wQu636WXuuzkmuL2jgeUHTAREdR3ehDHv2EKAw

![falx 1](https://github.com/user-attachments/assets/c572f3b7-0ea7-4d55-8c8d-677931b3d21f)

**Comment by Khan-arsh** [comment]
@KiwiAzz85 Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Lissanro** [comment]
Warning: I deleted scammer's fake message. In case you received fake message to your email, do not click any links!

**Comment by Jk0x0kJ** [comment]
closed due to inactivity
