### ISSUE TITLE
Currency does not change

### ISSUE THREAD

**Issue by Tdjc919** [FalconX-DEX/Falx-Support#46]
In the app on the swapping page there is the price chart, which shows the price of FALX or other tokens. However, when you have for instance selected SOL/FALX it shows not the price of SOL in the FALX currency, but just the FALX price in dollars. If you want to show the dollar price you should add it to the y axis that it is in dollars. 

So, to summarise, it should be clear that the shown price is not the price of the pair, but just of the token you are swapping to in dollars.

If you have questions about this, let me know.

**Smartphone (please complete the following information):**
 - Device: SAMSUNG A52
 - OS: Android
 - Browser Phantom browser
 - Version (?)

**Comment by Lissanro** [comment]
Thank you for your feedback. We will have a major update soon, once it is completed, I will add an indication that the price in the chart is in dollar units. I will update the issue when it is completed.

**Comment by Lissanro** [comment]
We adjusted in a way that the chart shows value based on input and output tokens, with current dollar value of each token being shown in the swap form itself. Hopefully this will make both the chart and the swap farm easier to use, and will provide more intuitive experience.
