### ISSUE TITLE
Unstaking of non-FalX assets fail

### ISSUE THREAD

**Issue by KKydd77** [FalconX-DEX/Falx-Support#47]
**Describe the bug**
When I try to unstake non-FalX tokens I get a "This transaction reverted during simulation ." error on Phnatom confirm transaction screen. Proceeding with the transaction results in an error on Solscan.

**To Reproduce**
1. Go to any staked token besides FalX
2. Click on unstake
3. Confirm the transaction
4. See error 'This transaction reverted during simulation' 

**Expected behavior**
Expected behavior is a normal transaction confirmation message that shows the token being unstaked in green being added to your wallet balance and SOL and FalX in red for gas and unstake tax.

**Screenshots**
<img width="357" alt="Screenshot 2024-09-09 at 7 46 03 AM" src="https://github.com/user-attachments/assets/5023cf2b-1673-4e61-84ac-91d7724b6097">

<img width="1381" alt="Screenshot 2024-09-09 at 7 54 28 AM" src="https://github.com/user-attachments/assets/36df445d-eef1-4911-8ea0-b97c50783ba7">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.6.1
 - Browser: Brave
 - Version 1.69.162

**Additional context**
My suspicion is that the 1% FalX tax has no way of being collected from non-FalX tokens and it's causing the transaction to fail.

**Comment by Khan-arsh** [comment]
@KKydd77 Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Lissanro** [comment]
Warning: I deleted scammer's fake message. In case you received fake message to your email, do not click any links!

**Comment by KKydd77** [comment]
When you try to unstake a non-FalX asset how does the 1% tax get paid? I'm assuming it needs to be collected in FalX token? Do you need to have enough pending rewards to cover 1% of what you are withdrawing?

**Comment by KKydd77** [comment]
This seems to be a Brave issue. I installed my wallet on Chrome and tried it and it unstaked as expected. Please close this issue at your convenience.
