### ISSUE TITLE
can i change wallet for distributing SOLX

### ISSUE THREAD

**Issue by ArtjomGrom** [FalconX-DEX/Falx-Support#48]
I am a SOLX holder and receive a reward weekly. Can I change my wallet so that the reward goes to a new one? Best regards!

**Comment by Tonytech-wq** [comment]
@ArtjomGrom Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Lissanro** [comment]
Warning: I deleted scammer's fake message. In case you received fake message to your email, do not click any links!

Sorry, the airdrop list is fixed after the phase was completed when the addresses were collected and checked. Good news is that you can just accumulate tokens on your old wallet and transfer them to a new one, Solana gas fees are very low.
