### ISSUE TITLE
Staking - Pending Rewards - $0 shown with FALX balance present

### ISSUE THREAD

**Issue by StonkSquatch** [FalconX-DEX/Falx-Support#49]
![Screenshot_20240913_232733_Phantom](https://github.com/user-attachments/assets/ec855ca5-2cfd-4ec0-9f37-4056897cbe39)

Platform: Mobile, Galaxy S21, Android, Phantom Wallet Browser. 

$ amount for Pending Rewards is zero when there is a FALX balance shown.

Prior & expected behavior is that the application displays a calculated dollar value for the pending FALX balance based on current FALX token price.

I've closed the page and reopened it a couple of times over the past 7 hours.

If no one else is seeing this issue, I could be in an edge case scenario where perhaps this issue resolves at my next 24h reward drop.

**Comment by NKMUC** [comment]
I have the same problem and withdrawing it brings up an error message

**Comment by Lissanro** [comment]
Should be fixed. Please make sure to refresh the page to see the update.

**Comment by StonkSquatch** [comment]
Verified fix.
Nice work team!
