### ISSUE TITLE
Not getting staking rewards

### ISSUE THREAD

**Issue by mkashifk5574** [FalconX-DEX/Falx-Support#50]
**Describe the bug**
Since 2 days I am not getting any rewards.

<img width="1462" alt="Screenshot 2024-09-14 at 08 10 11" src="https://github.com/user-attachments/assets/afc12280-542f-4217-81f3-311ca7545d21">

staking history:
<img width="1514" alt="Screenshot 2024-09-14 at 08 11 17" src="https://github.com/user-attachments/assets/bff6874e-ab4c-4ce6-99ff-c2ce758cca3d">

**Comment by Lissanro** [comment]
Thank you for reporting an issue. Do you have an issue with harvesting, or that pending reward did not increase after 24 hours as expected? Please provide what wallet app and browser you are using (for example, Phantom wallet in Chrome), and your wallet address, so we can investigate the issue.

**Comment by mkashifk5574** [comment]
Pending rewards did not increase after 24hrs.
Using Phantom wallet in chrome on a mac.
Address is Hjt6XmePU7NDQKq6MLzTawctFM19HGKPYGHhDdSQAKRR

**Comment by Jk0x0kJ** [comment]
I’ve checked the numbers, and the total amount is 13,415.79932023. Each day, they receive 3,353.75, with rewards being distributed after the day ends (starting from the moment they harvest their reward).

So, The number showing is right. If you see incorrect number it means the time for the bag(s) not completed yet.


Let me know if you need any further details!
