### ISSUE TITLE
Swap is now working properly.

### ISSUE THREAD

**Issue by Tdjc919** [FalconX-DEX/Falx-Support#52]
**Describe the bug**
Check the swapped falx amount in the 4 screenshots. The first seems ok (even though price impact is higher than what it says), second also. However in the third and 4th screenshot you see that the swap amount does not change even though I pay more SOL.

**Smartphone (please complete the following information):**
 - Device: Samsung A52 
 - OS: Android
 - Browser Phantom
 
![Screenshot_20240914_135929_Phantom](https://github.com/user-attachments/assets/a04d7bfe-ca56-4324-83c9-debcad1cc20a)
![Screenshot_20240914_135933_Phantom](https://github.com/user-attachments/assets/70fa06a9-c946-41c8-9208-df9e4a2086dc)
![Screenshot_20240914_135938_Phantom](https://github.com/user-attachments/assets/49151ace-6f27-4a25-bf0e-212bfced8e88)
![Screenshot_20240914_135943_Phantom](https://github.com/user-attachments/assets/84d41f4e-fd43-476a-8769-657003bcc0c9)

**Comment by Lissanro** [comment]
I could not reproduce the issue on Samsung Note20 Ultra with Phantom browser, it works reliably on my end. Do you still experience the issue?

**Comment by Tdjc919** [comment]
No, the issue has dissapeared.
