### ISSUE TITLE
Cannot swap USDT into any coins e.g. LIKE, SAND, CAVE

### ISSUE THREAD

**Issue by jilam07** [FalconX-DEX/Falx-Support#53]
**Describe the bug**
Cannot swap USDT into any coins e.g. LIKE, SAND, CAVE  in faldex, but I can see and do so in Raydium.
Router should make it work, right? Is it something wrong and needs fixes?
Besides, USDC can be swapped to most of the coins. However, cannot swap USDC into TUGER or DOPA.

**To Reproduce**
1. Go to 'Swap'
2. Choose 'USDT' in the swap from coin
3. Choose coins e.g. LIKE, SAND, or CAVE  in the swap to coin
4. Cannot click SWAP to finish

**Expected behavior**
Can swap USDT into LIKE, SAND, or CAVE via router

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Android
 - Browser: Phanthom

**Additional context**

**Comment by jilam07** [comment]
Besides, USDC can be swapped to most of the coins. However, cannot swap USDC into TUGER or DOPA.

**Comment by Lissanro** [comment]
![Screenshot_20240916_125635](https://github.com/user-attachments/assets/048e8a19-afa9-4d2c-8a8f-74eae944b0f3)

Do you still have the issue with LIKE, SAND or CAVE? I tried all three with USDC as the input, and Swap button worked for them all, offering to perform the exchange.

As of USDC to DOPA, I think there is no liquidity pool for it yet, someone may need to create a liquidity pool first.

**Comment by Jk0x0kJ** [comment]
Closed due to inactivity, Feel free to reopen if needed.

**Comment by jilam07** [comment]
DOPA to USDT doesn't work
