### ISSUE TITLE
Staking page under maintenance

### ISSUE THREAD

**Issue by 420LT** [FalconX-DEX/Falx-Support#55]
I’ve cleared cache closed all windows restarted all apps and phone. Staking rewards page still shows it is under maintenance

**Comment by Lissanro** [comment]
It is not under maintenance. it is possible you are not completely cleared the cache. Please provide more details if you still have the issue. In what browser and OS you have the issue? What URL you visit specifically? What other browsers you have tried?

**Comment by 420LT** [comment]
I’m on phantom wallet and using iOS. I cleared web history from both safari and chrome. I’m on Falxdex.com

**Comment by 420LT** [comment]
Cleared cache once more, staking page was showing under maintenance again. I hit the refresh button and that solved my problem. I’m able to see my staking page normally

**Comment by Lissanro** [comment]
Thank you for taking your time to try various solutions. Glad to hear refreshing the page helped to solve the issue!
