### ISSUE TITLE
Incorrect staking rewards amount for the last 2 days.

### ISSUE THREAD

**Issue by Alterego0690** [FalconX-DEX/Falx-Support#56]
I usually get a daily staking reward amount of 53,852 but the last 2 days I did not receive the full amount. I have a pending rewards amount of 2,207,942 it should be 2,290,129.  Im missing 82,187 of my staking rewards. Im using Phantom wallet in chrome. wallet address: 
I am on Mac IOS 
Browser: Chrome 

**Additional context**

**Comment by Jk0x0kJ** [comment]
Just a quick note—timing is key for rewards. I noticed an 8-minute gap between the last bag and the one you got rewarded for. Next time, consider waiting until all your bags are eligible, then withdraw them together.

Let me know if you have any questions!

@Alterego0690

**Comment by Alterego0690** [comment]
I just harvested today a little after 6am. I been letting it build up for a little over a 1 1/2 months. during the time of the issue I did not harvest I would just check it daily to make sure staking came before I left to start my day. so it cant be user error. It happened the day after the router went online and the day after I got less then normal daily rewards.

**Comment by Alterego0690** [comment]
Its cool. No problem. I know you are hard at work dealing with bigger issues like dev work. My staking rewards are back to normal after those days so Im not complaining over a day one of two missed. Thanks for looking into it. Great Job so far Dev Team. The FalX Family is behind you all the way. LETS F#$KING GOOO!!!!
