### ISSUE TITLE
LP Remove not possible plus display error on mobile phone 

### ISSUE THREAD

**Issue by ino89** [FalconX-DEX/Falx-Support#58]
LP remove not possible always comes a mistake 

at 25% 50% 75% and 100% 

Here is the link from Solscan. 

https://solscan.io/tx/2QeuYFnJzNLNR1T851wmEkiwf5XHK2wVBk4eWWrAsdYR5t58nBuXL2DxJ5Pe2WVTXn3Cdp6vDPnYRvWXDekSK8Vn

Here's a video of what it looks like when I click on the question mark. 

https://github.com/user-attachments/assets/192dd317-c1fe-4c50-9d45-c8abf6a01e9a

**Comment by ino89** [comment]
Okay the take-off works but the display error as in the video is still present.

**Comment by Jk0x0kJ** [comment]
This issue has been fixed with our `0x2_651v2` update last night.

Feel free to reopen if needed.
