### ISSUE TITLE
Google search improvement

### ISSUE THREAD

**Issue by Moinhaus** [FalconX-DEX/Falx-Support#6]
If you search for falxdex at google you still get the .io page.
I suggest to either put an google add out So the .com comes out on top or create a redirect from .io to .com so people will always get to the right page.

**Comment by Lissanro** [comment]
Thank you for letting us know. We already added our new domain in the Google Console so it should soon come up on top once Google index it for the first time. I just submitted a request to Google to remove the old domain from the search results in the meantime, it should not take long for them to process it, so I am closing this as solved.
