### ISSUE TITLE
Unable to harvest staked reward

### ISSUE THREAD

**Issue by CKS9999** [FalconX-DEX/Falx-Support#61]
**Describe the bug**
Cannot harvest from FALX

I have tried multiple times to harvest but same error meesage "Failed harvest". Have tried clearing cache and also checked to have enough SOL.

Note. I had same issue about 1 month ago and problem was soved by your team but seeing the same problem again. 

To Reproduce

Go to 'Stake pool'
Click on 'Harvest'
Show 'Waiting for Confirmation'
but then See error 'Failed harvest' and cannot receive FALX

**Comment by jilam07** [comment]
I used to experience this. Matt told me to have $5 worth FALX in my wallet.
I bought FALX $5 worth and can harvest now
