### ISSUE TITLE
Uncle Sal Token

### ISSUE THREAD

**Issue by UncleSalToken** [FalconX-DEX/Falx-Support#63]
**Describe the bug**
Hash error coming up when trying to swap USAL/Sol

**To Reproduce**
1. Go to '...' swap
2. Click on '....'usal/sol
3. Scroll down to '....'swap
4. See error hash error

**Expected behavior**
We had several people buy USAL when we launched but several people messaged to report the hash error so I tested and can confirm

**Screenshots**
I can't down load i
![signal-2024-09-18-16-51-56-439](https://github.com/user-attachments/assets/4f99f123-2132-4857-b50c-7229f22748a9)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung
 - OS: [e.g. iOS8.1] current 
 - Browser [e.g. stock browser, safari] stock
 - Version [e.g. 22] s23

**Additional context**

**Comment by Jk0x0kJ** [comment]
Closed to due inactivity!

Feel free to re-open if needed.
