### ISSUE TITLE
Unable to harvest staked reward

### ISSUE THREAD

**Issue by CKS9999** [FalconX-DEX/Falx-Support#64]
Cannot harvest from FALX staked reward. My wallet address is 

I have tried multiple times to harvest but same error meesage "Failed harvest". Have tried clearing cache and also checked to have enough SOL.

Note. I had same issue about 5 days ago and problem was soved by your team but seeing the same problem again. 

To Reproduce

Go to 'Stake pool'
Click on 'Harvest'
Show 'Waiting for Confirmation'
but then See error 'Failed harvest' and cannot receive FALX

**Comment by Hudini3** [comment]
having same issue. takes my gas fee but thats it.

**Comment by myvioletau** [comment]
i have the same issue, the error :"failed harvest"

**Comment by myvioletau** [comment]
try now guys, it works just now for me
i dont know why it is working now, i still want the tech team to check it and make sure harvest will always work for us
