### ISSUE TITLE
failed harvest

### ISSUE THREAD

**Issue by myvioletau** [FalconX-DEX/Falx-Support#65]
**Describe the bug**
today, i cant harvest, the error says: "failed harvest"

i tried multiple times, all failed with the same error
i have about 9000 falx in the balance, 
it was ok yesterday
my wallet address is :

CSdsPxHRq4DqiU7JMFQv6RzkFWPg4BiGY9NJdbvE3rez

thanks!

**Comment by myvioletau** [comment]
i tried just now and harvest is ok now!
i dont know why it is ok now

**Comment by myvioletau** [comment]
i dont know why it is working now , please make sure the harvest work for us all the time, it is not working sometimes, while i always to make sure i have enough SOL and at least 8000 falx tokens in the wallet before i harvest, but sometimes, harvest failed

**Comment by Lissanro** [comment]
Thank you for reporting the issue.  We will double check everything if it is possible to improve from our side. Glad to hear it is resolved now, so I am closing it.
