### ISSUE TITLE
failed harvest

### ISSUE THREAD

**Issue by harrison6673** [FalconX-DEX/Falx-Support#66]
I have phanton app on android. when trying to harvest, it fails. I have enough sol and falx. 

address is DcUNT1V2odAbeveE9C41c3KSbHm1eHUAgnz4nZ1qasBj

thanks

**Comment by myvioletau** [comment]
try now guys, it works just now for me

**Comment by Lissanro** [comment]
Others reported this as solved, but please feel free to request reopening if you still have the issue.
