### ISSUE TITLE
Unable to Harvest Falx Token

### ISSUE THREAD

**Issue by Luqman77Kai** [FalconX-DEX/Falx-Support#67]
**Describe the bug**
I am unable to harvest the rewards for my staked Falx token. I already cleared the cache and restart the browser. I have more than enough Solana (5$) and Falx (8$) in my phantom wallet. But still the Failed Harvest notification pops out whenever I tried to harvest. 

I think there lots of user that had face the same issue as me. 
Below is my phantom wallet address:
GwKMBDgE1Gih19sJQrcSs8kZFNnC2YJ3sf3YRFSweAmU

**Comment by myvioletau** [comment]
try now guys, it works just now for me

**Comment by Luqman77Kai** [comment]
I am able to do it now. The case is closed
