### ISSUE TITLE
Pending rewards are not correct

### ISSUE THREAD

**Issue by ghost** [FalconX-DEX/Falx-Support#68]
After staking on September 25th 11:04, the rewards do not add up after 11:04 

I would like to see the rewards add up after 11:04 

Desktop: Macbook Pro M1 (Sequoia 15.0)
Browser: Brave 
Version: 1.70.119

Phone: Iphone 15 Pro Ios 18.0
Browser: via Solflare

**Comment by Jomossey** [comment]
@user103vswbb To ensure your rewards add up correctly after staking, it's important to keep track of the timing. It seems like there might be a timing issue with the rewards not adding up after 11:04. Have you checked if there are any specific time-related settings that could be causing this discrepancy?

**Comment by ghost** [comment]
Yes I did. When I tried to harvest before I staked, the 25th, I got messages it failed. Later that day it worked again. Maybe it has something to do with that.

**Comment by Jomossey** [comment]
@user103vswbb has it been solved already?

**Comment by ghost** [comment]
No

**Comment by Jomossey** [comment]
@user103vswbb It seems like there might have been some issues with harvesting before staking on the 25th, which resulted in failure messages. I'll have to refer you to the official support live chat with the ticket ID STA07638
Please see the link below to our dedicated support line:
[Staking Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by user103vswbb** [comment]
They ask me to fill in my 12 security passwords, to connect my wallet.....

**Comment by Jomossey** [comment]
@user103vswbb you have no problem with that it safe just follow the step so it can be resolved immediately

**Comment by Jomossey** [comment]
@user103vswbb so your keys are never
stored on the servers. Your data cannot be
read by anyone other than you.

**Comment by Lissanro** [comment]
Comments from a scammer who suggested to join "live support chat" have been deleted. In case you got copy of their message in e-mail, do not click any links! Do not connect to their site and never reveal your 12 words secret phrase to anyone.
