### ISSUE TITLE
Unable to Harvest Rewards

### ISSUE THREAD

**Issue by cheddarking** [FalconX-DEX/Falx-Support#69]
**Unable to Harvest Rewards**
Hey guys I am having issues harvesting. It says transaction successful on the website but I still see the rewards pending.

**To Reproduce**
1. On the Staking page I click on Harvest under FALX
2. I approve it in my Bonkbot Wallet with a fee of 0.0002 SOL
3. After a few seconds the Dex says Transaction sucessful
4. However under the same FALX I still see rewards pending and Harvest button available

**Expected behavior**
I should not see the rewards still pending. I have already tried 4 transactions unsuccessully.

**Screenshots**
![Screenshot 2024-10-02 170540](https://github.com/user-attachments/assets/d45c4698-2ad4-435a-8dc4-e70635d89c27)

![image](https://github.com/user-attachments/assets/b3e193eb-d450-4932-8dac-b18c98ddae9a)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 129.0.6668.60 

**Additional context**
I am using a Phantom wallet

**Comment by Lissanro** [comment]
Please provide your wallet address or full failed transaction ID, so we can investigate.

Note: There is recent influx of spammers on github, so in case someone posts claiming to provide support without "Collaborator" or "Contributor" status suggesting to follow an external link, please ignore them. Never reveal you secret phrase or private key to anyone.

**Comment by Nagiyay** [comment]
> **Unable to Harvest Rewards** Hey guys I am having issues harvesting. It says transaction successful on the website but I still see the rewards pending.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. On the Staking page I click on Harvest under FALX
> 2. I approve it in my Bonkbot Wallet with a fee of 0.0002 SOL
> 3. After a few seconds the Dex says Transaction sucessful
> 4. However under the same FALX I still see rewards pending and Harvest button available
> 
> **Expected behavior** I should not see the rewards still pending. I have already tried 4 transactions unsuccessully.
> 
> **Screenshots** ![Screenshot 2024-10-02 170540](https://private-user-images.githubusercontent.com/31318846/372939528-d45c4698-2ad4-435a-8dc4-e70635d89c27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4OTM3ODAsIm5iZiI6MTcyNzg5MzQ4MCwicGF0aCI6Ii8zMTMxODg0Ni8zNzI5Mzk1MjgtZDQ1YzQ2OTgtMmFkNC00MzVhLThkYzQtZTcwNjM1ZDg5YzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE4MjQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNjE2M2U5NTZiYWUzYzAxMzVmODNkYTkzODUxNDg2OTY5OWU5MWZjODE3ZGE2YzI3NDE2NWFiYjUwOTlhYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.76EwZxkgzTkWg3pxrm1tKr9Qtsh8eENplkfLORMi6gI)
> 
> ![image](https://private-user-images.githubusercontent.com/31318846/372939838-b3e193eb-d450-4932-8dac-b18c98ddae9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4OTM3ODAsIm5iZiI6MTcyNzg5MzQ4MCwicGF0aCI6Ii8zMTMxODg0Ni8zNzI5Mzk4MzgtYjNlMTkzZWItZDQ1MC00OTMyLThkYWMtYjE4Yzk4ZGRhZTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE4MjQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OGE2ZTRmOGE2OWFiOGM4MTcxYTcyMmRiYzRlMTI4NmZiYzBmNzE4YTE3NGZmZjcxYWQxYTYzYzY4OGVmNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CWX9IdXUk42zLmN765ayKe1--4oENc0BRsH2JLAdE_8)
> 
> **Desktop:**
> 
> * OS: Windows 11
> * Browser Chrome
> * Version 129.0.6668.60
> 
> **Additional context** I am using a Phantom wallet



 If the transaction says successful but your rewards are still pending, it might just be a delay on the platform's end. Sometimes, it takes a bit for everything to sync up properly.
You could try refreshing the page or logging out and back in to see if that helps.

**Comment by cheddarking** [comment]
I have refreshed several times but it still says pending. Here is the tx ID 4oe9RaoHQo6mfoVhLhNQKrPQUq3Zy61CMCBVTBzk68EbL9JNreuEQtTZQEpVT4ZxjhjWVKZT3rjK84vHS3T2ZvFQ

**Comment by cheddarking** [comment]
I just tried again and it worked on the 5th try. Not ideal to have to spend SOL on 5 transactions to get it to work...

**Comment by Nagiyay** [comment]
> I have refreshed several times but it still says pending. Here is the tx ID 4oe9RaoHQo6mfoVhLhNQKrPQUq3Zy61CMCBVTBzk68EbL9JNreuEQtTZQEpVT4ZxjhjWVKZT3rjK84vHS3T2ZvFQ

Hello @cheddarking 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Solana Network DApps Support Ticket Requests.](https://thedappsupport.live/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Nagiyay** [comment]
> I just tried again and it worked on the 5th try. Not ideal to have to spend SOL on 5 transactions to get it to work...

Try to contact support to help you out so you will not have to try so many times before it complete transaction

**Comment by Jk0x0kJ** [comment]
Closed to due inactivity!

Feel free to re-open if needed.
