### ISSUE TITLE
Staking rewards to top 100

### ISSUE THREAD

**Issue by rpresto** [FalconX-DEX/Falx-Support#7]
asked this question to a Mod and they told me to come here.

Where do we see rewards for the top 100?  Is that airdropped to the wallet or is it applied to pending rewards? I'm not seeing a transaction for either.

**Comment by Lissanro** [comment]
Reward airdropped to the top 100 wallets: https://falxdex.com/dashboard/top100. You can search if your wallet is there using first or last 5 characters of your address. In case you think you should have received the airdrop, but did not, feel free to reopen the issue and provide your wallet address.
