### ISSUE TITLE
Have not been receiving my weekly staking rewards from top 100 staking .

### ISSUE THREAD

**Issue by hamerod** [FalconX-DEX/Falx-Support#73]

**Comment by Troy-ling** [comment]
Hi there @hamerod ! 
Please check your staking status, reward schedule, and transaction history using a blockchain explorer, andIf the issue persists, I recommend contacting the support team for further assistance.

I've already submitted a support ticket for you with ID FLX7638. Please reference this when reaching out: [Falx Staking Dapps Support Ticket Requests](thedappsupport.com).

You’ll find a live chat bubble in the bottom right corner of the page. Click it to start a conversation with a support agent who can help resolve the issue quickly.

For urgent help, live chat is the fastest option.

Thank you for your patience, and I hope this is resolved soon!

**Comment by Lissanro** [comment]
Comments from a scammer who suggested to join "live support chat" have been deleted. In case you got copy of their message in e-mail, do not click any links!

**Comment by Jk0x0kJ** [comment]
This issue has been closed due to inactivity!

Feel free to re-open if needed!
