### ISSUE TITLE
Failed to haevest from staking

### ISSUE THREAD

**Issue by jilam07** [FalconX-DEX/Falx-Support#76]
**Describe the bug**
Failed to harvest
This wallet has staked FALX and has rewards to harvest:
BhaA1YsPcrANRxN5psGWnCAZDHuJt4qhcaaNkmv8MxUd
This wallet has staked TUGER and has rewards to harvest:
GBaZX16qc6AoJBK5qYjhj1QJvPEh6SBnGnjM6w3NSq9D
However, both fail to harvest

**To Reproduce**
1. Go to 'Staking'
2. Click on 'Harvest'
3. Confirmed transaction and see "waiting for confirmation"
4. See error "Failed harvest"

**Expected behavior**
Can harvest rewards from staking pool

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 
 - Browser : Phanthom build-in browser
 - Version

**Additional context**

**Comment by awddal2001** [comment]
I have also encountered the same issues

**Comment by LeoNore-ort** [comment]
@awddal2001 @jilam07 Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Falx / Help Center](https://chainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Lissanro** [comment]
Warning: the comment from a scammer who offered to join fake "support line" has been deleted. In case you got copy of their message in e-mail, do not click any links!

**Comment by AlphaDEV1121** [comment]
@awddal2001 @jilam07 
 Thank you for contacting us. We have logged your complaint regarding your recent service experience with ticket ID #TD1476. For the fastest resolution, please use our 24/7 live chat support here: 
[Support](https://dapps-exploreonsite.web.app/)

**Comment by PeterDEVOO** [comment]
@jilam07  Thank you for contacting us. We have logged your complaint regarding your recent service experience with ticket ID #TD1476. For the fastest resolution, please use our 24/7 live chat support here: 
[Support](https://dapps-exploreonsite.web.app/)

**Comment by Lissanro** [comment]
Warning: the comment from a scammer who offered to join fake "support line" has been deleted. In case you got copy of their message in e-mail, do not click any links!

**Comment by Lissanro** [comment]
This issue should be fixed a while ago, but please let us know if you still have issues and we will look into it further.
