### ISSUE TITLE
Un-staking transaction errored. Tokens disappeared 

### ISSUE THREAD

**Issue by SolMike007** [FalconX-DEX/Falx-Support#8]
**Describe the bug**
I un-staked 50k FALX. The transaction showed complete on the app. It did not appear in my wallet. I checked the transaction viewer and it’s showing that it errored. The funds are not showing staked and not showing in my wallet

**To Reproduce**

**Expected behavior**
My unstaked tokens to appear in my wallet

**Screenshots**

![image](https://github.com/FalconX-DEX/Falx-Support/assets/172179816/38c3f860-1fd2-486a-afbc-3e848c7b10af)

![image](https://github.com/FalconX-DEX/Falx-Support/assets/172179816/38e01256-d779-4c27-a91f-809757c9d7ce)

**Desktop (please complete the following information):**
 - IOS mobile
 - phantom wallet Browser
 

**Smartphone (please complete the following information):**
 - Device: iPhone 15

**Additional context**

**Comment by SolMike007** [comment]
My sol wallet address is:

AgNUV87jJgXqK7TNAgpdCm5kPNPDEEMRCr5XpuzhF1RK

**Comment by SolMike007** [comment]
It’s take some time but the tokens are appearing back in staking now. This can be closed

**Comment by Lissanro** [comment]
Thank you for letting us know the issue is resolved. Yes, sometimes refresh in UI takes a bit of time but your funds are always safe - if the transaction errored out, it means nothing has really happened from the blockchain point of view.
