### ISSUE TITLE
LP Rewards Claimed via 'Claim your LP profit' button, but no rewards are in my Solflare Wallet. 

### ISSUE THREAD

**Issue by cjeffs** [FalconX-DEX/Falx-Support#82]
LP Rewards Claimed via 'Claim your LP profit' button, but no rewards in my Solflare Wallet. 

LP dashboard claims it was successful.

Solflare wallet being used on Firefox wallet browser extension.

**Comment by Lissanro** [comment]
Could you please share your wallet address?

**Comment by cjeffs** [comment]
I'd rather DM it to keept it private.

**Comment by Lissanro** [comment]
Please do. You can DM me the address via Telegram @Lissanro - I will forward the information to our blockchain dev.

**Comment by Purtos9** [comment]
Bonjour sur le pool sol/falx avec le nouveau bouton apparue pour retirer les profits LP mes transactions sont bien accepté mais je ne les voit pas sur mon phantom quelq'un pourrais t'il me dire où vont t'elle merci bonne journée

**Comment by cjeffs** [comment]
Resolved now thank you.

**Comment by Purtos9** [comment]
Super merci beaucoup bonne journée

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Purtos9** [comment]
❤️❤️
