### ISSUE TITLE
Nouveau bouton Profit LP sur pool 

### ISSUE THREAD

**Issue by Purtos9** [FalconX-DEX/Falx-Support#83]
.Hello I have a problem for LP profits with the new button appearing on the pool each time profits are withdrawn my transactions are confirmed but on my phantom wallet the amount does not change thank you for your help I hope that the translation and Well, I’m French.

**Comment by Annawoody** [comment]
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID PHA07638
Please see the link below to our dedicated support line:
[phantom Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@Purtos9

**Comment by Lissanro** [comment]
Warning: the comment from a scammer who offered to join fake "support line" has been deleted. In case you got copy of their message in e-mail, do not click any links! Never reveal your secret phrase or private key to anyone no matter what they say.

**Comment by Lissanro** [comment]
Please provide your wallet address or the transaction ID.

**Comment by Purtos9** [comment]
Bonjour merci voilà 6SxBvFmqBhJSNudy2KjS6erdojqJHpyqor7GjDTkLSq3

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lissanro** [comment]
This issue should be fixed, but if you experience the issues again, please let us know.

**Comment by Purtos9** [comment]
Ok super merci je ne sais pas comment fermer le ticket
