### ISSUE TITLE
Liquidity missing after partial deduction

### ISSUE THREAD

**Issue by Cvexi1985** [FalconX-DEX/Falx-Support#84]
After couple of attempts to withdraw total amount of liquidity(and failed transactions) i managed to withdraw with 75 %. I got more or less exact amount i was supposed to but after transaction i no longer have size in the pool( should be still 25 % of starting amount i had since i withdrew 75%) 
If needed i can provide screenshot from solscan to check my liquidity status.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kieth314M7** [comment]
@Cvexi1985 Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [FalconX Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Lissanro** [comment]
Warning: the comment from a scammer who offered to join fake "support ticket" has been deleted. In case you got copy of their message in e-mail, do not click any links!

**Comment by Lissanro** [comment]
Please provide your wallet address or transaction ID.

**Comment by Cvexi1985** [comment]
Wallet address: 

FVR3h72kCu1YF14BXPxSBT5Jr6cSaVnP6Mbtvr9Fxh8A

**Comment by Lissanro** [comment]
This issue should be fixed, can you please confirm?

**Comment by Cvexi1985** [comment]
Yes, issue fixed!!All is good.Thx a lot for promp solution!Falxdex team is like no other, best out there..Just keep rocking!👏

**Comment by Lissanro** [comment]
Great, thank you for confirming it is fixed! If you encounter any issues in the future, please feel free to open a new ticket.
