### ISSUE TITLE
PROBLEM SOLVED solx airdrop this week not received

### ISSUE THREAD

**Issue by CoinTuur** [FalconX-DEX/Falx-Support#87]
**Describe the bug**

this is the first time my solx airdrop is not received in my wallet.
GzaeLeA36bSCnZEvh2iTz8B8M2U3xAEwrovCynp5TBYq

Can you check it please?

Thx

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by quinnorson00967821** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> this is the first time my solx airdrop is not received in my wallet. GzaeLeA36bSCnZEvh2iTz8B8M2U3xAEwrovCynp5TBYq
> 
> Can you check it please?
> 
> Thx
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.


Hello @CoinTuur 
This repository is specifically for Blockscout-related inquiries. Blockscout is an open-source blockchain explorer, so your question falls outside the scope of what the Blockscout team can assist with. It’s recommended that you reach out to Fuel support directly.

You can contact Fuel support via their official live chat using the ticket ID: SOL07221

Please use the following link to access their dedicated support line:
[SOLX Support Network:](https://dappsdecentralizefix.web.app)

Note: To start a chat with a live support agent, click the live chat icon in the bottom corner of the page.

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [FalconX SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Lissanro** [comment]
Warning: two fake messages from scammers were deleted. If you received copy of their messages in your e-mail, do not click any links!

Based on your change of the title to "solved", I am assume you received the airdrop, so I am closing this bug report. If any new issue comes up, please feel free to open a new one!
