### ISSUE TITLE
Claimed Pool Rewards Not Showing in Wallet

### ISSUE THREAD

**Issue by juju068** [FalconX-DEX/Falx-Support#88]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I recently claimed my pool rewards, but they haven’t appeared in my wallet yet. Could you please help me figure out what to do next?

**Comment by marks909** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by MuahZain-Tech** [comment]
Hello @juju068 
Thanks for reporting this…. Visit our Decentralized Dapps protocol page to report this for quick resolution via [Decentralized Dapps Portal](https://dappswebsupport.com/) and complete your requests.
Note: We do not have any "Help Center"
Be careful

**Comment by Lissanro** [comment]
Warning: two scam messages have been deleted. If you got their copy I email, please do not click any links!

**Comment by Lissanro** [comment]
Please provide your wallet address or txid of the claiming transaction.

**Comment by juju068** [comment]
3iHHambV7VCHZdb7wNC7eaRZGeKpEswvyKBEEmAqbAqP

**Comment by juju068** [comment]
3iHHambV7VCHZdb7wNC7eaRZGeKpEswvyKBEEmAqbAqP

**Comment by Lissanro** [comment]
Thank you for your report. Please note that according to the blockchain data, you have received the reward 5 days ago:
https://solscan.io/tx/QWADf8EpJjYqvqmHoSAWdrofZSy8mLKidTwtDjjcY7WyxrEt7zLTaBttgtYxritdincC6ycMZAtAwiNjS7shjMr

Perhaps you missed it, but the link to the transaction should be help you to confirm it. Since you already received, I am closing this bug report as solved.

**Comment by juju068** [comment]
Five days ago, I received 10.6k FALX as part of the top 100 rewards. I was
referring to the LP reward when I mentioned this. While claiming the LP
reward, it showed approximately 36k FALX. However, as you can see, it is
not showing in my wallet.
