### ISSUE TITLE
Airdrop not received since 9/12

### ISSUE THREAD

**Issue by CHUDLPGC** [FalconX-DEX/Falx-Support#89]
**Describe the bug**
Following address has not received weekly airdrop since 9/12.

7Q9xV3KewrP6cDNrNisDup6g4K4C8hsQgKNL92WbP8uS

Thanks for your time

**Comment by Jk0x0kJ** [comment]
Hi,

Your airdrop already sent, you can check from following tx: 
https://solscan.io/tx/44T9Mgi4QZjyXsYWKgBJ3Q8xHHXCTCmkBZhUe5Jdb1dreLJ3Gc66vHWun6zFf8wvhQrwZ8rzRHvqqCP5rmq3EkiB

<img width="1567" alt="Screenshot 2024-12-28 at 11 50 26 pm" src="https://github.com/user-attachments/assets/be51e785-9617-48b9-8589-318926488798" />
