### ISSUE TITLE
Harvest is failing 

### ISSUE THREAD

**Issue by JackSacali** [FalconX-DEX/Falx-Support#9]
When harvesting, the transaction is giving a confirmation, transaction fees are gone (0.0002 SOL) but later the harvest fails.

**To Reproduce**
1. Go to 'staking'
2. Click on 'Harvest'
3. Confirm from Phantom wallet
4. Transaction give a confirmation in ~10 to ~20 seconds
5. Pending Rewards are gone (temporarily)
6. I don't receive the FLAX in my wallet
7. After ~1 minute I get another notification says 'Failed harvest'
8. I can see back the same Pending Rewards amount after a few minutes

**Expected behavior**
Receive the Pending Rewards in my wallet

**Screenshots**
![Screenshot 2024-06-13 at 17 19 51](https://github.com/FalconX-DEX/Falx-Support/assets/20048398/d5dc8fa8-9364-40bb-83a3-e077a8b79a2d)

![Screenshot 2024-06-13 at 17 20 18](https://github.com/FalconX-DEX/Falx-Support/assets/20048398/dad93f8b-b421-4c6e-993a-d55fbe5163bf)

I tried on both:
**Desktop**
 - OS: iOS 14.5
 - Browser chrome
 - Version  125.0.6422.142

**Smartphone (please complete the following information):**
 - Device: Pixel 8 pro
 - OS: Android 14
 - Browser Phantom browser
 - Version latest

**Additional context**
I tried 3 times and the same is happening every time, twice on mobile and once on desktop
Transaction fees: [1](https://solscan.io/tx/3TdaQGbNYo29Y1DwpbcGKhiF1Cbs4YYQYinbPXbG72DpwQGFaXhnkGRbdgReVWez3uwjPXj52MjiSDM5wkuqfygh), [2](https://solscan.io/tx/5K62CSXu2C1x8yyynmUPxREQVGppdxeJADWT6UcNN7QqLjQURnG1b22mfC6T1cbmN8mHmiSTVRmYWJ56E3hwzoQP), [3](https://solscan.io/tx/673LLKUixhQoCN2FoujW2hv7h4TTCWSQFBu5Hd8AFfbvSdkiGbThSAYCoR8wCdiQ5KyzVxzYszFQWC3tCKspav6K)

I was able to save two tranasactions that showed as confirmed on the Dapp:
[mobile](https://explorer.solana.com/tx/2pPxhXgKWztXB9sGbqsiQXk4JvSqCCnjYssju7zdAAT9CoyN95WDQWuZMVAVsntpDhPdib52oKMNeVa26i3HrTMi?cluster=mainnet-beta), [desktop](https://explorer.solana.com/tx/46KjHf1ZiKPo1rjPvcQkQfSL9E43ShbTvfG4SJ9xD1aJWh3tT3x2DNekqx1tTDTxFxvKftUXp4y4hcDpBVXSv1eK?cluster=mainnet-beta)
Both are giving not found

**Comment by cedricf50** [comment]
Same issue for me. Fees are gone and falx token stay on pending rewards

Édit : ok for me today, harvest works

**Comment by cheddarking** [comment]
Same here. I am using Phantom wallet

**Comment by Jk0x0kJ** [comment]
After our triage, we identified that during certain time periods, all RPC providers occasionally return a null hash according to high activity of the Solana network. This issue causes actions to be placed in the failure queue. The failure queue attempts to process these actions at intervals of 10 minutes. If unsuccessful, it reverts the action and clears the queue. If you try again, the issue should no longer occur.

Thank you for the well-formatted issue report you provided. We will close this issue for now, but if the problem persists, please feel free to reopen it and provide us with additional information.

@JackSacali
