### ISSUE TITLE
Weekly airdrop for SOLX not received.

### ISSUE THREAD

**Issue by Kazbeat** [FalconX-DEX/Falx-Support#90]
**Describe the bug**
I haven't received the airdrop that was supposed to drop on Monday the 23rd of December, 2024. 

The only missing drop since the beginning of SOLX airdrop.

This is my wallet address:

GWACvXqEiCPMXMchsAfdvHoDEtk71oYkqWvHC4CEHntf

Please help look into this issue and rectify ASAP.

Thanks 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Lissanro** [comment]
Warning: scammer's message has been deleted. If you received a copy of it in your email, do not open any links!

**Comment by Jk0x0kJ** [comment]
Your airdrop already sent with following tx:

https://solscan.io/tx/4iHHfXVKFiNER7JeWxqkZUFCtAoZJYWsSjLRZ3QFAd4ADG469HVcF3AMhyj5LyKmrRLqdqRqgfXdERnNN1H9hQef

<img width="1584" alt="Screenshot 2024-12-28 at 11 52 14 pm" src="https://github.com/user-attachments/assets/28fcd283-a790-4684-a8bd-646a5ba00caf" />
